oi_swot_4nadir: /home/administrateur/.datasets/ssh_NATL60_swot_4nadir.nc
pseudo_obs: /home/administrateur/.datasets/dataset_nadir_0d_swot.nc

natl_ssh_daily: /home/administrateur/.datasets/NATL60-CJM165_NATL_ssh_y2013.1y.nc
natl_sst_daily: /home/administrateur/.datasets/NATL60-CJM165_NATL_sst_y2013.1y.nc
natl_u_daily: /home/administrateur/.datasets/NATL60-CJM165_NATL_u_y2013.1y.nc
natl_v_daily: /home/administrateur/.datasets/NATL60-CJM165_NATL_v_y2013.1y.nc
